### ISSUE TITLE
MetalLB and Nginx Ingress Controller (Problem occurred while accessing nginx app with Host name)

### ISSUE THREAD

**Issue by basavrajdevpuje** [justmeandopensource/kubernetes#106]
I have followed the YouTube video on MetalLB and Nginx ingress controller.

I followed the steps from the video. But when I try to access the Nginx app using the host name (for e.g. nginx.example.com), I get the message "This site can't be reached".

My system details:

OS : Windows 10
K8s cluster : 
- set up using Kubeadm tool on Virtualbox
- One MASTER, one WORKER node
- server image :  ubuntu 18.04

Here is the description:

**The ingress-controller service**
```
NAMESPACE       NAME                                 TYPE           CLUSTER-IP       EXTERNAL-IP     PORT(S)                      AGE
default         kubernetes                           ClusterIP      10.96.0.1        <none>          443/TCP                      107m
default         nginx-deploy-k8s                     ClusterIP      10.106.72.22     <none>          80/TCP                       48m
default         nginx-deploy-main                    ClusterIP      10.102.198.254   <none>          80/TCP                       48m
ingress-nginx   ingress-nginx-controller             LoadBalancer   10.106.35.146    10.76.130.240   80:31825/TCP,443:32616/TCP   78m
ingress-nginx   ingress-nginx-controller-admission   ClusterIP      10.100.179.49    <none>          443/TCP                      78m
kube-system     kube-dns                             ClusterIP      10.96.0.10       <none>          53/UDP,53/TCP,9153/TCP       107m
```

The ingress-nginx-controller service have the external ip `10.76.130.240`

**The Ingress-resource**
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource
spec:
  rules:
  - host: nginx.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-deploy-main
            port:
              number: 80
  - host: k8s.nginx.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-deploy-k8s
            port:
              number: 80
```
**The deployment and services** 
```
master@master:~/k8s-objects$ kubectl get all
NAME                                     READY   STATUS    RESTARTS      AGE
pod/nginx-deploy-k8s-7f8798b66c-r58km    1/1     Running   1 (21m ago)   62m
pod/nginx-deploy-main-5b4bd69c98-7vmhb   1/1     Running   1 (21m ago)   62m

NAME                        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
service/kubernetes          ClusterIP   10.96.0.1        <none>        443/TCP   120m
service/nginx-deploy-k8s    ClusterIP   10.106.72.22     <none>        80/TCP    61m
service/nginx-deploy-main   ClusterIP   10.102.198.254   <none>        80/TCP    61m

NAME                                READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/nginx-deploy-k8s    1/1     1            1           62m
deployment.apps/nginx-deploy-main   1/1     1            1           62m

NAME                                           DESIRED   CURRENT   READY   AGE
replicaset.apps/nginx-deploy-k8s-7f8798b66c    1         1         1       62m
replicaset.apps/nginx-deploy-main-5b4bd69c98   1         1         1       62m
```

And the `/etc/hosts` file:

```
127.0.0.1       localhost.localdomain   localhost
::1             localhost6.localdomain6 localhost6

10.76.130.240 nginx.example.com k8s.nginx.example.com

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
..........
..........
```

The message I am  getting when I try to access `nginx.example.com` is

![image](https://user-images.githubusercontent.com/68498809/175570823-4af797f2-62b4-4023-813c-f75df8d3338c.png)

Could you help me to figure out the issue?

Thank you in advance.
