### ISSUE TITLE
lxd driven provisioning k8s with kubespray

### ISSUE THREAD

**Issue by MatthiasHertel** [justmeandopensource/kubernetes#17]
hi venkat,

first of all thanks for the great playground repo - it inspires me a lot! :)

i tried to install k8s with kubespray on lxc container, and i got some trouble with it.
i used the profile, but i have to disable the fail-on-swap check with an ignore_erros flag. kubespray will fail on the swap check. see diff on kubespray repo:

```
diff --git a/roles/kubernetes/preinstall/tasks/0010-swapoff.yml b/roles/kubernetes/preinstall/tasks/0010-swapoff.yml
index 99587ac0..5174a4b8 100644
--- a/roles/kubernetes/preinstall/tasks/0010-swapoff.yml
+++ b/roles/kubernetes/preinstall/tasks/0010-swapoff.yml
@@ -16,3 +16,4 @@
 - name: Disable swap
   command: /sbin/swapoff -a
   when: swapon.stdout
+  ignore_errors: yes
\ No newline at end of file
(END)
```

i wonder why swap is always on with the given k8s-profile from here:

https://raw.githubusercontent.com/justmeandopensource/kubernetes/master/lxd-provisioning/k8s-profile-config

the free command show swap is on:
```
lxc exec kmaster -- free -m
              total        used        free      shared  buff/cache   available
Mem:           1907         120         917           8         869        1787
Swap:         16335          53       16282
```

k8s-profile:

```
config:
  limits.cpu: "2"
  limits.memory: 2GB
  limits.memory.swap: "false"
  linux.kernel_modules: ip_tables,ip6_tables,netlink_diag,nf_nat,overlay,ip_vs,ip_vs_rr,ip_vs_wrr,ip_vs_sh
  raw.lxc: "lxc.apparmor.profile=unconfined\nlxc.cap.drop= \nlxc.cgroup.devices.allow=a\nlxc.mount.auto=proc:rw
    sys:rw"
  security.nesting: "true"
  security.privileged: "true"
description: LXD profile for Kubernetes
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: k8s-profile
used_by:
- /1.0/containers/ubuntu1804
- /1.0/containers/kworker1
- /1.0/containers/kmaster
```

in addition to that i had to add some kernel_module to the k8s-profil (ip_vs)

furthermore i wonder about this line 7days ago .... 
what is that  for?

https://github.com/justmeandopensource/kubernetes/commit/3f55019dd5c69d041087c47f0493cad5b6169da5#diff-b6b693b8386e0f20c807566b467f894fR53
kind regards!
matthias
