### ISSUE TITLE
persistentvolumeclaim/pvc-nfs-pv1 pending

### ISSUE THREAD

**Issue by YumiSuki** [justmeandopensource/kubernetes#52]
I am learning dynamic provisioning but couldn't make it to work properly. I have tried the original code provided by this repository and it's working but when I tried to make a minor change to docker image, it's stop working. 
First I have done `kubectl apply -f  kubernetes/yamls/nfs-provisioner/rbac.yaml`. Next I have done `kubectl apply -f   kubernetes/yamls/nfs-provisioner/class.yaml` without any error. Then I applied the following deployment: 
```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deploy
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx-deploy
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: nginx 
          volumeMounts:
            - name: nfs-client-root
              mountPath: /usr/share/nginx/html
          env:
            - name: PROVISIONER_NAME
              value: example.com/nfs
            - name: NFS_SERVER
              value: 10.0.10.25
            - name: NFS_PATH
              value: /srv/nfs/kubedata
      volumes:
        - name: nfs-client-root
          nfs: 
            server: 10.0.10.25
            path: /srv/nfs/kubedata
```

Here is the output when I execute `kubectl get pv,pvc`:
```
NAME                                STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS          AGE
persistentvolumeclaim/pvc-nfs-pv1   Pending                                      managed-nfs-storage   112s
```

Here is the output when I execute `kubectl get pod,deployment`:
```
NAME                                  READY   STATUS    RESTARTS   AGE
pod/nginx-deploy-5d68cc4f69-f7jnm     1/1     Running   0          6m20s

NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/nginx-deploy     1/1     1            1           6m20s
```

Here is the output when I execute `kubectl describe persistentvolumeclaim/pvc-nfs-pv1`:
```
Name:          pvc-nfs-pv1
Namespace:     default
StorageClass:  managed-nfs-storage
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: example.com/nfs
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    <none>
Events:
  Type    Reason                Age                  From                         Message
  ----    ------                ----                 ----                         -------
  Normal  ExternalProvisioning  9s (x25 over 5m51s)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "example.com/nfs" or manually created by system administrator
```

So, why the status still pending and doesn't get bound?

**Comment by donevgoran** [comment]
Hey @YumiSuki,

I believe that your cluster is running on the latest version of kubernetes 1.20, the problem is with selfLink.

If you want to solve your problem with nfs provisioner, you need to add this line 
```
spec:
  containers:
  - command:
    - kube-apiserver
```
Add this line:
`**- --feature-gates=RemoveSelfLink=false**`
into 
/etc/kubernetes/manifests/kube-apiserver.yaml

For more information you can read here
https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/25
