### ISSUE TITLE
Need help for K8s multi master K8s

### ISSUE THREAD

**Issue by santoshyadav0106** [justmeandopensource/kubernetes#94]
I am preparing K8s cluster with below environment
-Ubuntu server 20.04.2 LTS
-Kubernetes version 1.22
-Runtime CRIO
-3 Node GlusterFS
-2 HA and Keepalive load balancer nodes
-2 Master nodes
-3 ETCD nodes
-4 Worker nodes

I am following your K8s-external-etcd document and video, but I am facing issues during kubeadm init with kubeadm-config.yaml
Can you please share the  sample for the kubeadm-config.yaml? how it can be created for my above environment?

Thanks in Advance.
Santosh Yadav

**Comment by ak2766** [comment]
I took a shortcut as I too couldn't find one anywhere.

I deployed a `KinD` cluster of `3 x control plane nodes` and `3 x worker nodes` then copied the `kubeadm` config file from the first control plane node (found @ `/kind/kubeadm.conf`) and then tailored it to for environment.

Hope that helps a little.

<details>
<summary>kubeadm.conf</summary>

```yaml
root@test-control-plane:/# cat /kind/kubeadm.conf 
apiServer:
  certSANs:
  - localhost
  - 127.0.0.1
  extraArgs:
    runtime-config: ""
apiVersion: kubeadm.k8s.io/v1beta2
clusterName: test
controlPlaneEndpoint: test-external-load-balancer:6443
controllerManager:
  extraArgs:
    enable-hostpath-provisioner: "true"
kind: ClusterConfiguration
kubernetesVersion: v1.19.1
networking:
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/16
scheduler:
  extraArgs: null
---
apiVersion: kubeadm.k8s.io/v1beta2
bootstrapTokens:
- token: abcdef.0123456789abcdef
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 172.19.0.5
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock
  kubeletExtraArgs:
    fail-swap-on: "false"
    node-ip: 172.19.0.5
    provider-id: kind://docker/test/test-control-plane
---
apiVersion: kubeadm.k8s.io/v1beta2
controlPlane:
  localAPIEndpoint:
    advertiseAddress: 172.19.0.5
    bindPort: 6443
discovery:
  bootstrapToken:
    apiServerEndpoint: test-external-load-balancer:6443
    token: abcdef.0123456789abcdef
    unsafeSkipCAVerification: true
kind: JoinConfiguration
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock
  kubeletExtraArgs:
    fail-swap-on: "false"
    node-ip: 172.19.0.5
    provider-id: kind://docker/test/test-control-plane
---
apiVersion: kubelet.config.k8s.io/v1beta1
evictionHard:
  imagefs.available: 0%
  nodefs.available: 0%
  nodefs.inodesFree: 0%
imageGCHighThresholdPercent: 100
kind: KubeletConfiguration
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
iptables:
  minSyncPeriod: 1s
kind: KubeProxyConfiguration
mode: iptables
```
</details>

**Comment by rubbercable** [comment]
Here's mine for kubeadm. Interesting features:
- crio sock
- advertisement of haproxy loadbalancer for multimaster (I updated the hostfiles on controllers and workers (.. or you could just use an IP address))
to-do: cgroups
- cgroup2 > systemd > cgroup


---
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
controlPlaneEndpoint: haproxy:6443
kubernetesVersion: v1.23.4
controllerManager:
  extraArgs:
    flex-volume-plugin-dir: "/etc/kubernetes/kubelet-plugins/volume/exec"
networking:
  podSubnet: 10.244.0.0/16
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration

nodeRegistration:
  criSocket: /var/run/crio/crio.sock

**Comment by rubbercable** [comment]
---
Here's mine for kubeadm. Interesting features:
- crio sock
- advertisement of haproxy loadbalancer for multimaster (I updated the hostfiles on controllers and workers (.. or you could just use an IP address))
- todo: migrate to cgroup2  (cgroup2 > systemd > cgroup1)

````
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
controlPlaneEndpoint: haproxy:6443
kubernetesVersion: v1.23.4
controllerManager:
  extraArgs:
    flex-volume-plugin-dir: "/etc/kubernetes/kubelet-plugins/volume/exec"
networking:
  podSubnet: 10.244.0.0/16
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration

nodeRegistration:
  criSocket: /var/run/crio/crio.sock
````
